---
# tasks file for ansible-role-rsyslog-client

- name: "Copy rsyslog config for clients that only ship logs"
  template: src=central_syslog.conf.j2 dest={{ syslog_conf_path }}/{{ central_conf_file }} owner=root group=root mode=0644 backup=yes
  notify: Restart rsyslog

- name: "Create location of remote logs"
  file: "path={{ central_logs_directory }} state=directory owner=root group=root mode=0755"
  when: central_log_listener

- name: Add logrotate for remote logs
  template: src=remote_logrotate.j2 dest=/etc/logrotate.d/remote_logrotate owner=root group=root mode=0644
  when: central_log_listener

